export const CREATE_NEW_ANIMAL = "CREATE_ANIMAL";
export const SET_NEW_ANIMAL_TO_LOADING = "SET_NEW_ANIMAL_TO_LOADING";
export const GET_ALL_ANIMALS = "GET_ALL_ANIMALS";
export const CLEAN_NEW_ANIMAL = "CLEAN_NEW_ANIMAL";
export const SET_FETCHED_ANIMALS_TO_LOADING = "SET_FETCHED_ANIMALS_TO_LOADING";
